name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd bee && go build -v ./...

    - name: Test
      run: cd bee && go test -v -coverprofile cover.out ./...
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy new version
      run: ./build.sh
      shell: bash
